version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wacpac_virtual_contest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/wacpac_virtual_contest?schema=public
      - PORT=5050
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres_data: 